//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.18 at 01:21:22 AM CET 
//


package com.project.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outboundTrainId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="returnTrainId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ticketType" type="{http://project.com/reservation}TicketType"/>
 *         &lt;element name="trainClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nbTickets" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outboundTrainId",
    "returnTrainId",
    "ticketType",
    "trainClass",
    "nbTickets"
})
@XmlRootElement(name = "addReservationRequest")
public class AddReservationRequest {

    protected int outboundTrainId;
    protected Integer returnTrainId;
    @XmlElement(required = true)
    protected String ticketType;
    @XmlElement(required = true)
    protected String trainClass;
    protected int nbTickets;

    /**
     * Gets the value of the outboundTrainId property.
     * 
     */
    public int getOutboundTrainId() {
        return outboundTrainId;
    }

    /**
     * Sets the value of the outboundTrainId property.
     * 
     */
    public void setOutboundTrainId(int value) {
        this.outboundTrainId = value;
    }

    /**
     * Gets the value of the returnTrainId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReturnTrainId() {
        return returnTrainId;
    }

    /**
     * Sets the value of the returnTrainId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReturnTrainId(Integer value) {
        this.returnTrainId = value;
    }

    /**
     * Gets the value of the ticketType property.
     * 
     * @return
     *     possible object is
     *     {@link TicketType }
     *     
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * Sets the value of the ticketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketType }
     *     
     */
    public void setTicketType(String value) {
        this.ticketType = value;
    }

    /**
     * Gets the value of the trainClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainClass() {
        return trainClass;
    }

    /**
     * Sets the value of the trainClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainClass(String value) {
        this.trainClass = value;
    }

    /**
     * Gets the value of the nbTickets property.
     * 
     */
    public int getNbTickets() {
        return nbTickets;
    }

    /**
     * Sets the value of the nbTickets property.
     * 
     */
    public void setNbTickets(int value) {
        this.nbTickets = value;
    }

}
